version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "juntossomosmais/loyalty"
      - "juntossomosmais/loja-virtual"
      - "juntossomosmais/core"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "juntossomosmais/loyalty"
      - "juntossomosmais/loja-virtual"
      - "juntossomosmais/core"