trigger:
  - master

pr:
  - master

parameters:
- name: vmImage
  type: string
  default: ubuntu-latest

stages:
- stage: Lint_Test
  pool:
    vmImage: ${{ parameters.vmImage }}
  condition: and(succeeded(), ne(variables['Build.Reason'], 'IndividualCI'))
  displayName: Lint and Test project
  jobs:
    - job: Lint
      displayName: Lint check the project
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.7'
            addToPath: true
            architecture: 'x64'
          displayName: "User python 3.7"
        - script: |
            FILE=.pre-commit-config.yaml
            if ! test -f "$FILE"; then
                echo "$FILE does not exists. Exiting the pre-commit linting stage with success."
                exit 0
            fi
            echo "$FILE exists. Installing pre-commit"
            export SETUPTOOLS_USE_DISTUTILS=stdlib
            python --version
            pip install pre-commit
            pre-commit run --all-files
          displayName: "Checks for .pre-commit-config.yaml on project root, lint checking if it does"
    - job:
      dependsOn: Lint
      condition: succeeded()
      displayName: Test project
      steps:
      - task: DockerCompose@0
        displayName: 'Run tests on Docker Compose service'
        inputs:
          containerregistrytype: 'Container Registry'
          dockerComposeCommand: 'up --abort-on-container-exit tests'
      - publish: $(System.DefaultWorkingDirectory)
        artifact: s
        displayName: 'Send artifact to sonar'

- stage: Sonar
  pool:
    vmImage: ${{ parameters.vmImage }}
  condition: and(succeeded(), ne(variables['Build.Reason'], 'IndividualCI'))
  displayName: Sonar
  jobs:
    - job:
      displayName: Sonar prepare, analyze an publish
      steps:
      - download: current
        artifact: s
        displayName: 'Get artifact from test'
      - task: SonarCloudPrepare@1
        displayName: 'Prepare analysis on SonarCloud'
        inputs:
          SonarCloud: SonarCloud
          organization: juntossomosmais
          scannerMode: CLI
      - task: SonarCloudAnalyze@1
        displayName: 'Run Code Analysis'
      - task: SonarCloudPublish@1
        displayName: 'Publish Quality Gate Result'

- stage: Publish_Artifact
  pool:
    vmImage: ${{ parameters.vmImage }}
  condition: and(succeeded(), ne(variables['Build.Reason'], 'IndividualCI'))
  displayName: Publish artifact
  jobs:
    - job:
      displayName: Publish artifact
      steps:
        - task: PublishBuildArtifacts@1
          displayName: "Publish Artifact: drop"
          inputs:
            PathtoPublish: ./

- stage: Publish_on_PyPI
  pool:
    vmImage: ${{ parameters.vmImage }}
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: Publish on PyPI
  jobs:
    - job:
      displayName: Publish on PyPI
      steps:
        - script: |
            set -e
            pip install poetry

            #DEV
            #poetry config http-basic.testpypi $(PYPI_JSM_USERNAME_TEST) $(PYPI_JSM_PASSWORD_TEST)
            #poetry publish -r testpypi

            #PROD
            poetry build
            poetry publish -u $(PYPI_JSM_USERNAME) -p $(PYPI_JSM_PASSWORD)
          displayName: 'Publish on PyPI'
        - script: |
            set -e
            
            set_variable(){
                echo "Set key $1 as $2"
                echo "##vso[task.setvariable variable=$1]$2"
            }
            
            LIB_VERSION=$(cat pyproject.toml | grep 'version' | head -1 | cut -d '"' -f 2)
            
            set_variable "TAG_VERSION" ${LIB_VERSION}
          displayName: 'Retrieve version from pyproject.toml'
        - task: GitHubRelease@1
          displayName: 'GitHub release (create)'
          inputs:
            gitHubConnection: 'jsm-robot-personal-access-token'
            tagSource: userSpecifiedTag
            tag: '$(TAG_VERSION)'
