version: "3.9"

# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile.dev

services:
  tests:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command:
      ["./scripts/start-tests.sh"]
    networks:
      - django-stomp-debug-callback-network

  lint-formatter:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command: ["./scripts/start-formatter-lint.sh"]
    networks:
      - django-stomp-debug-callback-network

  sonar:
    container_name: sonar
    image: mwizner/sonarqube:8.9.5-community # chip m1 mac
#    image: sonarqube:8-community
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    networks:
      - django-stomp-debug-callback-network

  sonar-cli:
    container_name: sonar-cli
    image: sonarsource/sonar-scanner-cli
    working_dir: /api
    environment:
      - SONAR_LOGIN=admin
      - SONAR_PASSWORD=test
    volumes:
      - .:/api
    command: ["sonar-scanner", "--debug"]
    networks:
      - django-stomp-debug-callback-network

networks:
  django-stomp-debug-callback-network: